name: check-commit-message
description: Check message meets convention
inputs:
  gh_token:
    description: Workflow repo's GITHUB_TOKEN
    required: false
    default: ${{ github.token }}
runs:
  using: node16
  main: dist/index.js
